### ISSUE TITLE
Having a compile Issue

### ISSUE THREAD

**Issue by ajaykumarkannan** [cando/GNOME-Journal#5]
I wanted to try out this application so I cloned it and I'm trying to compile it. After resolving several dependencies, on configure, it terminates with this error: 

checking for xgettext... (cached) /usr/bin/xgettext
./configure: line 12969: syntax error near unexpected token `0.9.6'
./configure: line 12969:`GOBJECT_INTROSPECTION_REQUIRE(0.9.6)'

I am trying to compile this on a Fedora 17 x64 system. 

Any ideas? 

Thanks.

**Comment by cando** [comment]
Thanks for the interest in our project. gobject-introspection and gobject-introspection-devel should be the packages you're searching for. Feedback from your testing is really appreciated.  :)

Cheers,

Stefano

**Comment by ajaykumarkannan** [comment]
Thanks. That dependency got resolved. I'm running into this now: 

configure: error: Package requirements (gtk+-3.0 >= 3.4.0
         glib-2.0
         clutter-1.0 >= 1.10
         clutter-gtk-1.0 >= 1.0.1
         gee-1.0
         zeitgeist-1.0
         gnome-desktop-3.0
         gio-2.0
         gio-unix-2.0
         ) were not met:

No package 'clutter-1.0' found
No package 'clutter-gtk-1.0' found
No package 'gee-1.0' found
No package 'zeitgeist-1.0' found
No package 'gnome-desktop-3.0' found

Doesn't make sense at all since I'm already running GNOME3 and I have this package installed:  gtk3-3.4.4-1.fc17.x86_64 which should satisfy the dependency. I couldn't find anything for gee but the others, I am pretty sure that I have the rest installed.

**Comment by cando** [comment]
First, update the code. I've just pushed a minor correction.
Second, you might have those packages but you don't have their devel packages. So you should have to install:
zeitgeist, libzeitgeist, libzeitgeist-devel, gnome-desktop3, gnome-desktop3-devel and ligbee06, libgee06-devel.

In this list i've included also the non-devel package in case you don't have them.

Cheers,

Stefano

**Comment by ajaykumarkannan** [comment]
Working now. Thanks. Will let you know about my take on it. 

Is there a wiki or help somewhere on usage? I've noticed two features which appear to be missing which are there in the original Activity Journal (Incognito mode and the delete item - Though it didn't allow multiple deletes in one go in that one) or am I just not using it properly?

**Comment by cando** [comment]
Fine. We don't have a wily and no, these features aren't still implemented: Feel free to open issues here in github.

Thanks for your testing. It's really appreciated.

----- Reply message -----
Da: "Ajaykumar Kannan" notifications@github.com
A: "cando/GNOME-Journal" GNOME-Journal@noreply.github.com
Cc: "Stefano Candori" stefano.candori@gmail.com
Oggetto: [GNOME-Journal] Having a compile Issue (#5)
Data: sab, set 1, 2012 19:01
Working now. Thanks. Will let you know about my take on it. 

Is there a wiki or help somewhere on usage? I've noticed two features which appear to be missing which are there in the original Activity Journal (Incognito mode and the delete item - Though it didn't allow multiple deletes in one go in that one) or am I just not using it properly?

&mdash;
